defaults:
- logger: print-logger

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${hydra.job.name}${...job_suffix}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${hydra.job.name}${...job_suffix}/${now:%Y-%m-%d}/${now:%H-%M-%S}

gpu: 0
job_suffix: ""