defaults:
- common
- optimizer: sgd
# - optimizer/learning_rate: expdecay
- _self_

data:
  nsamples: 100
  dim: 8
  # ydim: 1
  # zdim: 10
  batchsize: 10
  ntimesteps: 20 # number of time steps per sample
seed: 42
checkpointing:
  path: checkpoints
  rate: 50 # in epochs
model:
  time_constant: 5e-3
  recurrent_strength: 1.2
  nhidden: 1000
  hidden_noise: 0
  # output_noise: 1e-1
  output_noise: 0
hsic:
  gamma: 2
  sigma: 0.5
optimizer:
  learning_rate: 5e-4
  # learning_rate:
  #   init_value: 5e-4
  #   decay_rate: 0.9
  #   transition_steps: 5
  #   staircase: false
training:
  time_step: 1e-3
  lpf_time_constant: 5e-3
  nepochs: 10
  log_epochs: true
  log_interval: 20 # in steps
