defaults:
- common
- schedule: expdecay
- logger: print-logger
- _self_

data:
  nsamples: 100
  xdim: 100
  ydim: 1
  zdim: 10
  batchsize: 6
  ntimesteps: 20 # number of time steps per sample
seed: 42
checkpointing:
  path: checkpoints
  rate: 50 # in epochs
model:
  time_constant: 50e-3
  recurrent_strength: 1.2
  nhidden: 2000
  hidden_noise: 5e-6
  output_noise: 1e-2
hsic:
  gamma: 2
schedule:
  init_value: 1e-4
  decay_rate: 0.8
  transition_steps: 10
  staircase: true
training:
  time_step: 1e-3
  lpf_time_constant: 5e-3
  nepochs: 100
  log_epochs: true
  log_interval: 250 # in steps
